/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionario;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mensagens.FuncionarioWorker;
import mensagens.GerenciaDeptos;
import mensagens.MensagemFuncionario;

/**
 *
 * @author marina
 */
public class Interface extends javax.swing.JFrame {
    public static String IPCentral = "localhost";
    /**
     * Creates new form Funcionario
     */
    public Interface() {
        initComponents();
        Thread gerencia = new Thread(new GerenciaDeptos(this));
        gerencia.start();
        lb_entradasenhaatual.setText("-"); // colocar variavel da senha atual
        lb_entradasenhaanterior.setText("-"); // colocar variavel da senha anterior
    }
    
    public void erroConectarServidor(){
        JOptionPane.showMessageDialog(null, "Erro ao conectar na Central!", "Erro", JOptionPane.ERROR_MESSAGE);
    }

    /*void atualizasenha() {
        String senhaatual = lb_entradasenhaatual.getText(); // colocar variavel da senha atual
        lb_entradasenhaanterior.setText(senhaatual);

    }[/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lb_idguiche = new javax.swing.JLabel();
        lb_departamento = new javax.swing.JLabel();
        lb_senhaatual = new javax.swing.JLabel();
        lb_senhatual = new javax.swing.JLabel();
        lb_entradasenhaatual = new javax.swing.JLabel();
        lb_entradasenhaanterior = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tb_chamarproximasenha = new javax.swing.JToggleButton();
        listaDepto = new javax.swing.JComboBox<>();
        listaGuiche = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa do Funcionário");
        setMaximumSize(new java.awt.Dimension(500, 267));
        setMinimumSize(new java.awt.Dimension(500, 267));
        setPreferredSize(new java.awt.Dimension(500, 267));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 267));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_idguiche.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        lb_idguiche.setText("ID Guichê:");
        getContentPane().add(lb_idguiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        lb_departamento.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        lb_departamento.setText("Departamento:");
        getContentPane().add(lb_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 62, -1, -1));

        lb_senhaatual.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        lb_senhaatual.setText("Senha Anterior: ");
        getContentPane().add(lb_senhaatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        lb_senhatual.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        lb_senhatual.setText("Senha Atual:");
        getContentPane().add(lb_senhatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lb_entradasenhaatual.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        lb_entradasenhaatual.setText("____");
        getContentPane().add(lb_entradasenhaatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        lb_entradasenhaanterior.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        lb_entradasenhaanterior.setText("____");
        getContentPane().add(lb_entradasenhaanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 120, 470, -1));

        tb_chamarproximasenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tb_chamarproximasenha.setText("Chamar próxima senha");
        tb_chamarproximasenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_chamarproximasenhaActionPerformed(evt);
            }
        });
        getContentPane().add(tb_chamarproximasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, 40));

        listaDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeptoActionPerformed(evt);
            }
        });
        getContentPane().add(listaDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 63, 110, -1));

        listaGuiche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        listaGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaGuicheActionPerformed(evt);
            }
        });
        getContentPane().add(listaGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_chamarproximasenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_chamarproximasenhaActionPerformed
        tb_chamarproximasenha.setSelected(false);
        int guiche = Integer.parseInt((String) listaGuiche.getSelectedItem());

        if (listaDepto.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um departamento!", "Funcionário", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String departamento = (String) listaDepto.getSelectedItem();
  
        
        //tb_emAtendimento.setEnabled(true);
        //tb_chamarproximasenha.setEnabled(false);
        
        // chamar metodo pedirSenha da central;
        chamarProximaSenha(departamento, guiche);
        

    }//GEN-LAST:event_tb_chamarproximasenhaActionPerformed

    private void listaDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDeptoActionPerformed

    private void listaGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaGuicheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaGuicheActionPerformed

    public void atualizaDeptos(ArrayList<String> deptos){
        String selecionado = (String)listaDepto.getSelectedItem();
        
        listaDepto.removeAllItems();
        while ( ! deptos.isEmpty() ) {
            String umDepto = deptos.remove(0);
            listaDepto.addItem(umDepto);
        }
        listaDepto.setSelectedItem(selecionado);
    }
    
    public void chamarProximaSenha(String departamento, int guiche){
        try {
            FuncionarioWorker fw = new FuncionarioWorker(this, departamento, guiche);
            Thread t = new Thread(fw);
            t.start();
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }
    
    public void recebeSenha(String senha){
        if (senha.equals("erro")){
            JOptionPane.showMessageDialog(null, "Não há nenhuma senha a ser chamada.", "Funcionário", JOptionPane.INFORMATION_MESSAGE);
        } else {
            lb_entradasenhaanterior.setText(lb_entradasenhaatual.getText());
            lb_entradasenhaatual.setText(senha);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_departamento;
    private javax.swing.JLabel lb_entradasenhaanterior;
    private javax.swing.JLabel lb_entradasenhaatual;
    private javax.swing.JLabel lb_idguiche;
    private javax.swing.JLabel lb_senhaatual;
    private javax.swing.JLabel lb_senhatual;
    private javax.swing.JComboBox<String> listaDepto;
    private javax.swing.JComboBox<String> listaGuiche;
    private javax.swing.JToggleButton tb_chamarproximasenha;
    // End of variables declaration//GEN-END:variables
}
