/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painel;
import mensagens.PainelWorker;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author marina
 */
public class Interface extends javax.swing.JFrame {
   public static String IPCentral = "localhost";
   PainelWorker pw;
   public ArrayList<String> senhas = new ArrayList<String>();
   public ArrayList<String> guiches = new ArrayList<String>();
   
   public void erroConectarServidor(){
        JOptionPane.showMessageDialog(null, "Erro ao conectar na Central!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
   
    void AtualizarHora() {
        AtualizarHora hora = new AtualizarHora(lb_data);
        hora.mostrarData(true);
        Thread thHora = hora;
        thHora.start();
    }
   public void AtualizarSenha(){
        senhas.add(2,senhas.get(1));
        guiches.add(2,guiches.get(1));
        senhas.add(1,senhas.get(0));
        guiches.add(1,guiches.get(0));
                
    }
    public void MostrarPainel(){
       
        
        lb_entradasenhaatual.setText(senhas.get(0));// colocar valor da senha atual
        lb_entradaguicheatual.setText(guiches.get(0));
        lb_entradaultimasenha.setText(senhas.get(1));
        lb_ultimoguiche.setText(guiches.get(1));
        lb_entradapenultimasenha.setText(senhas.get(2));
        lb_penultimoguiche.setText(guiches.get(2));
         
        
    }
    
  
    /**
     * Creates new form Painel
     */
    public Interface() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        initComponents();
        senhas.add("-");
        senhas.add("-");
        senhas.add("-");
        guiches.add("-");
        guiches.add("-");
        guiches.add("-");
        
//        String senhaatual = "123";
//        senhas.add(0,senhaatual);
//        
//        String guiche = "4";
//        guiches.add(0,guiche);
       
        
        MostrarPainel();       
        AtualizarHora();
        
        pw = new PainelWorker(this);
        Thread tpw = new Thread(pw);
        tpw.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb_entradasenhaatual = new javax.swing.JLabel();
        lb_entradapenultimasenha = new javax.swing.JLabel();
        lb_entradaultimasenha = new javax.swing.JLabel();
        lb_senhaatual = new javax.swing.JLabel();
        lb_data = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lb_ultimoguiche = new javax.swing.JLabel();
        lb_penultimoguiche = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lb_entradaguicheatual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel de Atendimento");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 768));
        setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lb_entradasenhaatual.setFont(new java.awt.Font("Ubuntu Light", 1, 70)); // NOI18N
        lb_entradasenhaatual.setForeground(new java.awt.Color(204, 0, 0));
        lb_entradasenhaatual.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 30, 0, 0);
        getContentPane().add(lb_entradasenhaatual, gridBagConstraints);

        lb_entradapenultimasenha.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        lb_entradapenultimasenha.setText("___");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 10, 0, 0);
        getContentPane().add(lb_entradapenultimasenha, gridBagConstraints);

        lb_entradaultimasenha.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        lb_entradaultimasenha.setText("___");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 0);
        getContentPane().add(lb_entradaultimasenha, gridBagConstraints);

        lb_senhaatual.setFont(new java.awt.Font("Ubuntu Light", 1, 48)); // NOI18N
        lb_senhaatual.setText("Senha Atual:       Guichê:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 0, 0);
        getContentPane().add(lb_senhaatual, gridBagConstraints);

        lb_data.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        lb_data.setText("Data/Hora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 46, 0);
        getContentPane().add(lb_data, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel6.setText("Últimas Senhas Chamadas: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 20, 0, 0);
        getContentPane().add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 0, 0);
        getContentPane().add(jSeparator2, gridBagConstraints);

        lb_ultimoguiche.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        lb_ultimoguiche.setText("____");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 4, 0, 0);
        getContentPane().add(lb_ultimoguiche, gridBagConstraints);

        lb_penultimoguiche.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        lb_penultimoguiche.setText("____");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 4, 0, 0);
        getContentPane().add(lb_penultimoguiche, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel1.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 19, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel2.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 19, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel3.setText("Guichê:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 9, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel4.setText("Guichê:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 9, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 20, 0, 0);
        getContentPane().add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 20, 0, 0);
        getContentPane().add(jSeparator4, gridBagConstraints);

        lb_entradaguicheatual.setFont(new java.awt.Font("Ubuntu Light", 1, 70)); // NOI18N
        lb_entradaguicheatual.setForeground(new java.awt.Color(204, 0, 0));
        lb_entradaguicheatual.setText("Guichê");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 19, 0, 0);
        getContentPane().add(lb_entradaguicheatual, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lb_data;
    private javax.swing.JLabel lb_entradaguicheatual;
    private javax.swing.JLabel lb_entradapenultimasenha;
    private javax.swing.JLabel lb_entradasenhaatual;
    private javax.swing.JLabel lb_entradaultimasenha;
    private javax.swing.JLabel lb_penultimoguiche;
    private javax.swing.JLabel lb_senhaatual;
    private javax.swing.JLabel lb_ultimoguiche;
    // End of variables declaration//GEN-END:variables
}
